horsex = float(input('Insert the cords of the horse: '))
horsey = float(input('Insert the cords of the horse: '))
pointx = float(input('Insert the cords of the point: '))
pointy = float(input('Insert the cords of the point: '))
horsex = (int(horsex % 1 * 10))
horsey = (int(horsey % 1 * 10))
pointx = (int(pointx % 1 * 10))
pointy = (int(pointy % 1 * 10))
print('Horse in:(' + str(horsex) + ',' + str(horsey) + ')')
print('Point in:(' + str(pointx) + ',' + str(pointy) + ')')
